Update to Julia 1.0
JuliaLinearOptimizers/Simplex.jl pull request #5
Opened 2019-02-25 12:33 UTC by RenanOD

2019-02-25 13:56 UTC, abelsiqueira commented
Quando você acabar as modificações e estiver pronto para que eu revise, você pode
1- Adicionar um label "ready to go"
2- Me adicionar como reviewer.

2019-03-15 22:32 UTC, abelsiqueira requested changes
Thanks for the update. I made a lot of small changes. I did check the algorithm, though. It has become too confusing to simply follow the code. Let's hope that can be changed in the future.

2019-03-15 22:32 UTC, abelsiqueira commented on README.md
> +[![Build Status](https://travis-ci.org/RenanOD/Simplex.jl.svg)](https://travis-ci.org/RenanOD/Simplex.jl)
Here it should still be `JuliaLinearOptimizers`.

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +  λ = Array{Float64,1}(undef, m); d = Array{Float64,1}(undef, m)
Break lines, put `d` in the line below.

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +function simplexinv(c, A, b, 𝔹=0, invB=0; max_iter = 20000)
`B = 0` may lead to a type stability issue. Since `B` should be an `Array{Int,1}`, we could use `B = Int[]` as comparison.

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +  if 𝔹 == 0 # construct artificial problem
See above. `B == []`.

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +    A = [A sparse(Diagonal(signb))]
`spdiagm(0 => signb)`.

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +    invB = sparse(Diagonal(signb))
`spdiagm...`

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +  getλ!(λ,c,𝔹)
Use a uniform spacing rule. I prefer always separating. `gety!(y, c, B)`.

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +    getAcol!(d,A,ℕ[q])
Spacing

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +        dfrac = xB[k]/d[k]
Spacing `a / b`

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +      status = :Unbounded; break
New line

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +    subdot!(xB,d,xq) # update solution
Spacing

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +    E = one(zeros(m,m))
This looks awful. You just want the identity? Use `E = Matrix(1.0I, m, m)`. Though I would prefer the fix to stop using this.

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +    λ = invB'*λ # FIX
spacing in these 3 lines

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +      ℕ = setdiff(ℕ,n+1:n+m)
spacing

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +    if dot(xB, c[𝔹]) > eps(Float64)
This should be further analyzed. Does it happen? Is `c` being modified? Is `xB` close to 0 when it should be zero? Is there an example? Please open an issue.

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexinv.jl
> +          (abs(d[PivotAp]) >= eps(Float64)) ? break : q += 1
Remove `(...)`

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexluup.jl
> +  if (U == 0) U = sparse(Diagonal(signb)) end
`spdiam`

2019-03-15 22:32 UTC, abelsiqueira commented on src/simplexluup.jl
> +      if findlast(w.!=0) > p
Spacing

2019-03-15 22:32 UTC, abelsiqueira commented on test/generators/transport_problem.jl
> +    for j in (i - 1)*n + 1 : i*n
Just changing to `.= 1` doesn't work?

2019-03-15 22:32 UTC, abelsiqueira commented on test/runtests.jl
> +Pkg.add("GLPK")
Remove `add` from `runtests.jl`. Create `test/REQUIRE` and add `JuMP` and `GLPK` there.

2019-03-15 23:10 UTC, RenanOD commented
I'm working on it. Thanks for the suggestions!

2019-03-18 01:34 UTC, RenanOD commented
All requested changes are done.
Unfortunately, a bug occurred while testing simplexluup during the last Travis Build.
I'll try to fix this or at least change the tests so this random failures never happen.

2019-03-18 17:05 UTC, RenanOD commented
I reduced the size of the tranport problems in tests.
There were no failures testing the equivalent to 200 Travis Builds.
Should be ready now.

2019-03-18 18:07 UTC, abelsiqueira approved these changes

2019-03-18 18:07 UTC, merged